#!/bin/bash
# ====================================================
# 1. DNS FIX: /etc/resolv.conf मध्ये Nameservers ॲड करा
#    (यामुळे 'apt update' साठी इंटरनेट कनेक्शन मिळेल)
# ====================================================

echo "Temporarily setting Nameservers in /etc/resolv.conf..."

# 1.1. /etc/resolv.conf मधील सर्व मजकूर साफ करा.
sudo tee /etc/resolv.conf > /dev/null <<EOL
# Generated by custom_data script for temporary DNS fix
nameserver 8.8.8.8         # Google Public DNS
nameserver 168.63.129.16   # Azure Internal DNS (Reliable)
EOL

echo "DNS settings applied."

# ====================================================
# 2. NGINX INSTALLATION AND START
# ====================================================
echo "Starting system updates and Nginx installation..."

# 2.1. apt update (आता DNS काम करेल)
sudo apt update -y

# 2.2. Nginx इन्स्टॉल करा
sudo apt install nginx -y

# 2.3. Nginx सेवा सुरू करा आणि सक्षम करा
sudo systemctl start nginx
sudo systemctl enable nginx

# 2.4. स्टेटस चेक करा
echo "Checking Nginx service status:"
systemctl status nginx
